#!/usr/bin/env sh

set -a
. ~/.config/xdg.dirs
set +a

export TERM="xterm-256color"
export EDITOR="$(which nvim)"
export PAGER="$(which bat)"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export SSH_KEY_PATH="${HOME}/.ssh/id_rsa"
export HOSTFILE="${HOME}/.ssh/known_hosts"

#export INPUTRC="${XDG_USER_CONFIG_DIR}/inputrc"
#export HISTFILE="${XDG_USER_CACHE_DIR}/shell/$(basename ${SHELL})_history"

#export JAVA_HOME=

#export LUA_ROCKS_DIR=

#export CARGO_HOME="${XDG_USER_CACHE_DIR}/cargo"
#export CARGO_INSTALL_ROOT="${XDG_USER_DATA_DIR}/cargo"

#export STARSHIP_CONFIG="${XDG_USER_CONFIG_DIR}/starship/config.toml"
#export STARSHIP_CACHE="${XDG_USER_CACHE_DIR}/starship"
export PURE_POWER_MODE="modern"

export PATH="${PATH}:${HOME}/bin:${HOME}/.cargo/bin"

#PATH+=":${HOME}"

