[alias]
br = "build --release"
in = "install --all-features --bins"

[build]
rustdocflags = [
    "--document-private-items",
    "--default-theme=dark",
    "--sort-modules-by-appearance",
    "--enable-index-page",
]
incremental=true

