# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# match = [
#     "{{ name }}.plugin.zsh",
#     "{{ name }}.zsh",
#     "{{ name }}.sh",
#     "{{ name }}.zsh-theme",
#     "*.plugin.zsh",
#     "*.zsh",
#     "*.sh",
#     "*.zsh-theme"
# ]


[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
autoload = 'autoload -Uz {{ name }}'

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

# Lazy loading
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["fpath", "autoload"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

# [plugins.fast-syntax-highlighting]
# github = "zdharma/fast-syntax-highlighting"
# apply = ["defer"]

[plugins.starship]
inline = 'eval $(starship init zsh)'

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

# [plugins.zoxide]
# inline = 'zsh-defer -c "$(zoxide init zsh --cmd j)"'

