---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
    unbind: true
    normal:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'b', Char: "\n", Esc,]
      - action: [SwitchToMode: Pane,]
        key: [Char: 'p',]
      - action: [NewPane: ,]
        key: [Ctrl: 'p', Char: ' ',]
      - action: [SwitchToMode: Resize,]
        key: [Char: 'r',]
      - action: [SwitchToMode: Tab,]
        key: [Char: 't',]
      - action: [NewTab: ,]
        key: [Ctrl: 't',]
      - action: [SwitchToMode: Scroll,]
        key: [Ctrl: 's',]
      - action: [SwitchToMode: Move,]
        key: [Char: 'm',]
      - action: [Quit,]
        key: [Ctrl: 'q',]
      - action: [NewPane: Left]
        key: [Ctrl: 'h',]
      - action: [NewPane: Down,]
        key: [Ctrl: 'j',]
      - action: [NewPane: Right,]
        key: [Ctrl: 'l',]
      - action: [NewPane: Up,]
        key: [Ctrl: 'k',]
      - action: [MoveFocus: Left,]
        key: [Char: 'h',]
      - action: [MoveFocus: Right,]
        key: [Char: 'l',]
      - action: [MoveFocus: Down,]
        key: [Char: 'j',]
      - action: [MoveFocus: Up,]
        key: [Char: 'k',]
      - action: [FocusPreviousPane, SwitchToMode: Locked]
        key: [Ctrl: '[',]
      - action: [FocusNextPane, SwitchToMode: Locked]
        key: [Char: ']',]
      - action: [FocusNextPane,]
        key: [Char: '.', Char: "\t",]
      - action: [FocusPreviousPane,]
        key: [Char: ',', Char: '`',]
      - action: [Resize: Increase,]
        key: [Char: '+',]
      - action: [Resize: Decrease,]
        key: [Char: '-',]
      - action: [CloseFocus,]
        key: [Char: 'q',]
      - action: [CloseFocus, SwitchToMode: Locked,]
        key: [Char: 'x',]
    locked:
      - action: [SwitchToMode: Normal,]
        key: [Ctrl: 'b',]
    resize:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'b', Char: 'b', Char: "\n", Esc,]
      - action: [SwitchToMode: Pane,]
        key: [Char: 'p',]
      - action: [SwitchToMode: Tab,]
        key: [Char: 't',]
      - action: [SwitchToMode: Normal,]
        key: [Ctrl: 'r', Char: ' ', Char: 'n',]
      - action: [SwitchToMode: Scroll,]
        key: [Char: 's', Up, Down]
      - action: [SwitchToMode: Move,]
        key: [Char: 'm',]
      - action: [Quit]
        key: [Ctrl: 'q']
      - action: [Resize: Left,]
        key: [Char: 'h', Left,]
      - action: [Resize: Down,]
        key: [Char: 'j',]
      - action: [Resize: Up,]
        key: [Char: 'k',]
      - action: [Resize: Right,]
        key: [Char: 'l', Right,]
      - action: [Resize: Increase,]
        key: [Char: '=', Char: '+',]
      - action: [Resize: Decrease,]
        key: [Char: '-']
      - action: [MoveFocus: Left,]
        key: [Ctrl: 'h',]
      - action: [MoveFocus: Right,]
        key: [Ctrl: 'l',]
      - action: [MoveFocus: Down,]
        key: [Ctrl: 'j',]
      - action: [MoveFocus: Up,]
        key: [Ctrl: 'k',]
      - action: [FocusPreviousPane,]
        key: [Char: '`',]
      - action: [FocusNextPane,]
        key: [Char: "\t",]
      - action: [FocusPreviousPane, SwitchToMode: Locked,]
        key: [Char: ',', Char: '[',]
      - action: [FocusNextPane, SwitchToMode: Locked,]
        key: [Char: '.', Char: ']',]
    pane:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'b', Char: "\n", Char: 'b', Esc,]
      - action: [SwitchToMode: Resize,]
        key: [Char: 'r',]
      - action: [SwitchToMode: Tab,]
        key: [Char: 't',]
      - action: [NewTab: ,]
        key: [Ctrl: 't',]
      - action: [SwitchToMode: Normal,]
        key: [Ctrl: 'p', Ctrl: 'n']
      - action: [SwitchToMode: Scroll,]
        key: [Char: 's', Up, Down,]
      - action: [SwitchToMode: Move,]
        key: [Char: ' ', Char: 'm',]
      - action: [Quit,]
        key: [Ctrl: 'q',]
      - action: [MoveFocus: Left,]
        key: [ Ctrl: 'h', Left,]
      - action: [MoveFocus: Right,]
        key: [ Ctrl: 'l', Right,]
      - action: [MoveFocus: Down,]
        key: [ Ctrl: 'j', Down,]
      - action: [MoveFocus: Up,]
        key: [ Ctrl: 'k', Up,]
      - action: [SwitchFocus,]
        key: [Char: "\t"]
      - action: [NewPane: ,]
        key: [Char: 'n', Char: 'p',]
      - action: [NewPane: Down,]
        key: [Char: 'j',]
      - action: [NewPane: Right,]
        key: [Char: 'l',]
      - action: [NewPane: Left,]
        key: [Char: 'h',]
      - action: [NewPane: Up,]
        key: [Char: 'k',]
      - action: [CloseFocus,]
        key: [Char: 'x', Char: 'd', Backspace]
      - action: [ToggleFocusFullscreen,]
        key: [Char: 'f',]
      - action: [TogglePaneFrames,]
        key: [Char: 'z',]
      - action: [FocusPreviousPane,]
        key: [Char: ',', Char: '[',]
      - action: [FocusNextPane,]
        key: [Char: '.', Char: ']',]
    move:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'b', Esc, Char: "\n",]
      - action: [SwitchToMode: Pane,]
        key: [Char: 'p',]
      - action: [NewPane: ,]
        key: [Ctrl: 'p', Ctrl: 'n',]
      - action: [SwitchToMode: Tab,]
        key: [Char: 't',]
      - action: [NewTab: ,]
        key: [Ctrl: 't',]
      - action: [SwitchToMode: Resize,]
        key: [Char: 'r',]
      - action: [SwitchToMode: Normal,]
        key: [Char: 'n', Char: ' ',]
      - action: [SwitchToMode: Scroll,]
        key: [Char: 's']
      - action: [Quit]
        key: [Ctrl: 'q']
      - action: [MovePane: ,]
        key: [Char: 'm', Char: "\t"]
      - action: [MovePane: Left,]
        key: [Char: 'h', Left,]
      - action: [MovePane: Down,]
        key: [Char: 'j', Down,]
      - action: [MovePane: Up,]
        key: [Char: 'k', Up, ]
      - action: [MovePane: Right,]
        key: [Char: 'l', Right,]
      - action: [MoveFocus: Left,]
        key: [ Ctrl: 'h',]
      - action: [MoveFocus: Right,]
        key: [ Ctrl: 'l',]
      - action: [MoveFocus: Down,]
        key: [ Ctrl: 'j',]
      - action: [MoveFocus: Up,]
        key: [ Ctrl: 'k',]
      - action: [FocusPreviousPane,]
        key: [ Char: ',', Char: '[',]
      - action: [FocusNextPane,]
        key: [ Char: '.', Char: ']',]
    tab:
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'b', Ctrl: 't', Esc, Char: "\n",]
      - action: [SwitchToMode: Pane,]
        key: [Char: 'p',]
      - action: [SwitchToMode: Resize,]
        key: [Ctrl: 'r',]
      - action: [SwitchToMode: Normal,]
        key: [Char: 'n',]
      - action: [SwitchToMode: Scroll,]
        key: [Ctrl: 's']
      - action: [SwitchToMode: Move,]
        key: [Char: 'm',]
      - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
        key: [Char: 'r']
      - action: [Quit,]
        key: [Ctrl: 'q',]
      - action: [FocusPreviousPane,]
        key: [Char: ',',]
      - action: [FocusNextPane,]
        key: [Char: '.',]
      - action: [GoToPreviousTab,]
        key: [ Char: 'h', Left, Up, Char: 'k', Char: '[',]
      - action: [GoToNextTab,]
        key: [ Char: 'l', Right,Down, Char: 'j', Char: ']',]
      - action: [NewTab: ,]
        key: [ Char: ' ', Char: 't',]
      - action: [CloseTab,]
        key: [ Char: 'x', Char: 'c', Char: 'q',]
      - action: [MoveFocus: Left,]
        key: [ Ctrl: 'h',]
      - action: [MoveFocus: Right,]
        key: [ Ctrl: 'l',]
      - action: [MoveFocus: Down,]
        key: [ Ctrl: 'j',]
      - action: [MoveFocus: Up,]
        key: [ Ctrl: 'k',]
      - action: [GoToTab: 1,]
        key: [ Char: '1',]
      - action: [GoToTab: 2,]
        key: [ Char: '2',]
      - action: [GoToTab: 3,]
        key: [ Char: '3',]
      - action: [GoToTab: 4,]
        key: [ Char: '4',]
      - action: [GoToTab: 5,]
        key: [ Char: '5',]
      - action: [GoToTab: 6,]
        key: [ Char: '6',]
      - action: [GoToTab: 7,]
        key: [ Char: '7',]
      - action: [GoToTab: 8,]
        key: [ Char: '8',]
      - action: [GoToTab: 9,]
        key: [ Char: '9',]
      - action: [ToggleTab]
        key: [ Char: "\t",]
    scroll:
      - action: [SwitchToMode: Normal,]
        key: [Char: 'n',]
      - action: [SwitchToMode: Tab,]
        key: [Char: 't',]
      - action: [SwitchToMode: Locked,]
        key: [Ctrl: 'b', Char: ' ', Char: "\n", Esc,]
      - action: [SwitchToMode: Pane,]
        key: [Char: 'p',]
      - action: [SwitchToMode: Move,]
        key: [Char: 'm',]
      - action: [SwitchToMode: Resize,]
        key: [Ctrl: 'r',]
      - action: [ScrollToBottom,]
        key: [Ctrl: 'f',]
      - action: [Quit,]
        key: [Ctrl: 'q',]
      - action: [ScrollDown,]
        key: [Char: 'j', Down,]
      - action: [ScrollUp,]
        key: [Char: 'k', Up,]
      - action: [PageScrollDown,]
        key: [Ctrl: 'd', PageDown, Right, Char: 'l',]
      - action: [PageScrollUp,]
        key: [Ctrl: 'g', PageUp, Left, Char: 'h',]
      - action: [HalfPageScrollDown,]
        key: [Char: 'f',]
      - action: [HalfPageScrollUp,]
        key: [Char: 'u',]
      - action: [NewPane: ,]
        key: [Ctrl: 'n',]
      - action: [MoveFocus: Left,]
        key: [ Ctrl: 'h',]
      - action: [MoveFocus: Right,]
        key: [ Ctrl: 'l',]
      - action: [MoveFocus: Down,]
        key: [ Ctrl: 'j',]
      - action: [MoveFocus: Up,]
        key: [ Ctrl: 'k',]
      - action: [FocusPreviousPane,]
        key: [ Char: ',', Char: '[',]
      - action: [FocusNextPane,]
        key: [ Char: '.', Char: ']',]
    renametab:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'n', Char: ' ',]
        - action: [TabNameInput: [27] , SwitchToMode: Tab,]
          key: [Esc, Char: "\n",]
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'b', Esc]
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'r',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'm',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'n', Char: "\n", Char: ' ',]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Detach,]
          key: [Char: 'd',]
plugins:
    - path: tab-bar
      tag: tab-bar
    - path: status-bar
      tag: status-bar
    - path: strider
      tag: strider

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
# default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true
#   - false (default)
#no_pane_frames: true

# Choose the theme that is specified in the themes section.
# Default: default
#theme: default

# themes:
#   # True Color
#   default:
#     # [255,255,255]
#     fg: [50,100,100]
#     bg: [0,0,0]
#     black: [10,20,185]
#     red: [170,15,153]
#     green: [0,0,0]
#     yellow: [0,0,0]
#     blue: [0,0,0]
#     magenta: [0,0,0]
#     cyan: [0,0,0]
#     white: [255,102,102]
#     orange: [0,0,0]
# themes:
#   # 256-Color
#   default:
#     fg: 59
#     bg: 0
#     black: 130
#     red: 14
#     green: 6
#     yellow: 0
#     blue: 0
#     magenta: 0
#     cyan: 0
#     white: 0
#     orange: 0



# Default: normal
default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true
#   - false (default)
#disable_mouse_mode: true
