---@module "lazy"
---@type LazySpec
return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    branch = "master",
    opts = {
        ensure_installed = {
            "bash",
            "comment",
            "c",
            "cpp",
            "diff",
            "git_config",
            "git_rebase",
            "gitcommit",
            "gitignore",
            "javascript",
            "json",
            "lua",
            "luadoc",
            "make",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "rust",
            "toml",
            "vim",
            "vimdoc",
        },
        auto_install = false,
        highlight = { enable = true, additional_vim_regex_highlighting = false },
        indent = { enable = true },
    },
}
