
# Remove duplicates
typeset -U path
typeset -U fpath
typeset -U manpath
typeset -U cdpath

. ~/.config/shell/shellrc
. ~/.config/shell/alias.sh

[[ $fpath = *${HOME}/.zfunc* ]] || fpath=(${HOME}/.zfunc $fpath)

# TODO: Bind zls colors to dircolors string output
# TODO: Change dircolors to hold a string, not a bash cmd
#ZLS_COLORS=$(dircolors ~/.dircolors)
#export ZLS_COLORS

export ZELLIJ_CONFIG_DIR=$HOME/.config/zellij

export FZF_DEFAULT_COMMAND='fd --follow --type file --color=always'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--ansi --height=40% --layout=reverse --info=inline --border --margin=2 --padding=2"
export FZF_COMPLETION_TRIGGER='--'

