# ----------# ZSH Config #----------
# ----------+============+----------

# -- Modules {{{

autoload -Uz compinit && compinit

# }}}

# Completion {{{
# Ambiguous case matching and -/_ interchangability
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z-_}={A-Za-z_-}'

# Menu selection
zstyle 'completion:*' menu select=9

zstyle 'completion:*' select-scroll 0

# Colorize missteps
zstyle ':completion:*:warnings' format "No matches found for: %{%F{214}%}%d%{%f%}"

# activate approximate completion, but only after regular completion (_complete)
zstyle ':completion:::::' completer _complete _correct _expand _approximate _expand_alias

# limit to 3 errors
zstyle ':completion:*:approximate:*' max-errors 3 numeric

# Dont expand ~ to /.../.../
zstyle ':completion::expand:*' keep_prefix yes

# Formatting completion
zstyle ':completion:*:descriptions' format 'Completing %d'

# Colorize
zstyle ':completion:*' list-colors ''

# Hosts
hosts=($([ -r .ssh/known_hosts ] && cat .ssh/known_hosts | cut -d ' ' -f 1 | tr ',' '\n' | sort -u))
zstyle ':completion:*' hosts $hosts

# Load git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zfunc $fpath)

# CD
# filter bad values
zstyle ':completion:*:-command-:*' tag-order '!parameters reserved-words'

# }}}

eval "$(dircolors $HOME/.dircolors)"

jdoc () {
    javadoc -d ~/html -sourcepath "$1" -subpackages java -exclude
}

zmodload zsh/complist
zmodload zsh/nearcolor
zmodload zsh/zle
zmodload zsh/zleparameter

autoload -Uz vcs_info && vcs_info
autoload -U colors && colors
for COLOR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
    eval $COLOR='%{$fg_no_bold[${(L)COLOR}]%}'  #wrap colours between %{ %} to avoid weird gaps in autocomplete
    eval BOLD_$COLOR='%{$fg_bold[${(L)COLOR}]%}'
done
eval RESET='$reset_color'


alias shlint='shellcheck --enable=all --severity=style'

# Enter interactive mode after executing a python script
alias ppy='python3 -i'

# Print large text
alias fig='figlet -f banner3 -c -w100'

alias wh='whence -mv'

# Variables {{{
# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

export CORRECT_IGNORE=_*

export HISTFILE="~/.zsh_history"
export HISTSIZE=800

export PATH="$HOME/bin:/usr/local/sbin:$PATH"

#source "$HOME/.lessrc"
#source "$HOME/.zsh/prompt.zsh"
#source "$HOME/.zsh/alias.zsh"
source "$HOME/.config/zsh/alias.zsh"
source "$HOME/.config/zsh/options.zsh"
source "$HOME/.config/zsh/rp.zsh"
source "$HOME/.config/shell/alias.sh"
source "$HOME/.config/shell/env.sh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Git Fuzzy
export PATH="/Users/james/.zsh/plugins/git-fuzzy/bin:$PATH:/Users/james/Library/Python/3.9/bin"

# }}}

# Keybindings
bindkey "^n" accept-and-menu-complete

# ZPLUG PLUGINS {{{
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/b4b4r07/zplug ~/.zplug
fi
source ~/.zplug/init.zsh

# Better keybindings
zplug "jeffreytse/zsh-vi-mode"
# Load completion library for those sweet [tab] squares
zplug "lib/completion", from:oh-my-zsh
# System clipboard
zplug "lib/clipboard", from:oh-my-zsh
# Navigation
zplug "lib/directories", from:oh-my-zsh
# VCS
zplug "plugins/git", from:oh-my-zsh
# https://git.jpatrick.io/james/dotfiles/src/commit/ab918ab3b5a640f4a0b686cf6cb297c0dbe35524/zsh/zplug
# Directory Jumping
zplug "agkozak/zsh-z"

# Syntax highlighting for commands, load last
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:3

zplug load

# }}}

# vim:foldmethod=marker
