
# No external command found {{{
command_not_found_handler () {
	# Executed in a sub-shell
	print -P "%F{#e88a38}%BCommand not found:%b%f %U$0%u"
	return 127
}
# }}}

# Dircolors {{{
if [[ -f ~/.dircolors ]]; then
  eval $(dircolors -b ~/.dircolors)
fi
# }}}

# Extraneous Sources {{{

# Options 
source $ZDOTDIR/opts.zsh
# Aliases
source $ZDOTDIR/alias.zsh
# Completions
source $ZDOTDIR/completions.zsh
# Keybindings
source $ZDOTDIR/keys.zsh

# }}}

ricksay

# Sheldon {{{
eval "$(sheldon source)"
# }}}


# vim:foldmethod=marker
