
# Checks:
#   1. If we are in the base shell (Zellij will enter an infinitely recursive loop if not)
#   2. If we are in an interactive shell
if [[ $SHLVL -eq 1 && $- == *i* ]]; then
    sleep 0.001
    zellij
    # Exit with zellij's exit code once it's done
    exit $?
fi

# No external command found {{{
command_not_found_handler () {
	# Executed in a sub-shell
	print -P "%F{#e88a38}%BCommand not found:%b%f %U$0%u"
	return 127
}
# }}}

# Dircolors {{{
if [[ -f ~/.dircolors ]]; then
  eval $(dircolors -b ~/.dircolors)
fi
# }}}

# Named Directories {{{

hash -d workspace=~/workspace
hash -d dots=~/dotfiles
hash -d nvim-dots=~/dotfiles/nvim
hash -d docs=~/Documents

# }}}

# Extraneous Sources {{{

# Options 
source $ZDOTDIR/opts.zsh
# Aliases
source $ZDOTDIR/alias.zsh
# Completions
source $ZDOTDIR/completions.zsh
# Keybindings
source $ZDOTDIR/keys.zsh
# Misc. Custom
source $ZDOTDIR/custom.zsh
# Prompt
source $ZDOTDIR/prompt.zsh

# FZF
source $ZDOTDIR/fzf.zsh

# }}}

ricksay

# Sheldon {{{
eval "$(sheldon source)"
# }}}

# vim:foldmethod=marker

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
