#!/usr/bin/env bash

# Ensure we're in an interactive shell
if [ -z "$PS1" ]; then return; fi

# History
shopt -s histappend histreedit histverify
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=20000
export HISTTIMEFORMAT=" (  %b %d  -  %H:%M  )  ->  "

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


# Will print `Hello World` just before each prompt
# PROMPT_COMMAND=( "echo 'Hello World'" )

shopt -s cdspell dotglob extglob gnu_errfmt huponexit no_empty_cmd_completion nocaseglob nocasematch shift_verbose xpg_echo

# Jobs that fail in background report back immediately
set -o notify

# Better keybindings
set -o vi

# Don't exit immediately on EOF (default is 10 consecutive)
set -o ignoreeof

# TODO:
. $HOME/dotfiles/shell/setup_env.bash
. $HOME/dotfiles/shell/setup_alias.bash

eval "$(starship init bash)"

#[ -f ~/.fzf.bash ] && source ~/.fzf.bash


source /home/james/.config/broot/launcher/bash/br

